<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Textiu.co</title>
    <link rel="stylesheet" href="public/style/css/csstextiu.css">
</head>
<body>

<header id="header" class="bg-primary">
<div class="container">
<div class="column-2 brand-tex">
<img src="public/style/images/brand-textiu-gray.svg" alt="">
</div>

<div class="column-2 is-right">
<nav id="nav">
    <ul>
        <li><a href="#">Soluções</a></li>
        <li><a href="#">Empresa</a></li>
        <li><a href="#">Cases</a></li>
        <li><a href="#">Planos</a></li>
        <li><a href="#">Contato</a></li>
    </ul>
</nav>
</div>

</div>
</header>

    
</body>
<script type="text/javascript" src="public/style/js/functions.js"></script>
  <script type="text/javascript" src="public/style/js/jquery-3.6.0.min"></script>
</html>



